### ISSUE TITLE
channel name/hashtag with diacritics

### ISSUE THREAD

**Issue by uranixcz** [staltz/manyverse#100]
Manyverse doesn't recognize channel names with diacritics like # zemědělství which works in Patchwork. It creates a link only for the beginning letters without diacritics - # zem. In my language there are many words with different meanings if you omit diacritics. For example "koš" means bin but "kos" means blackbird. So it should be recognized as a whole or not at all.

**Comment by Powersource** [comment]
hmm yeah for #malmö the link turns into #malm 

And I was hoping at least the underlying parsing that creates the `mention` in the json would have parsed it correctly but looking there that's also "malm"

**Comment by Powersource** [comment]
i've moved this issue here https://gitlab.com/staltz/manyverse/-/issues/1619
