### ISSUE TITLE
patchwork cannot find manyverse( ios)

### ISSUE THREAD

**Issue by senhuawang** [staltz/manyverse#105]
Hello,staltz, I have some questions about the use of manyverse. Patchwork is installed on my computer and manyverse is installed on my iPhone. In the same network, patchwork cannot find ios manyverse, but the manyverse on another Android phone can be found. Is the ios version of manyverse working properly? In addition, is the function of manyverse connecting to pub normal? I tried it, but no success.Thanks a lot!

**Comment by staltz** [comment]
It's a bug and I fixed it already but the fix will be published in a new version next week

**Comment by staltz** [comment]
See https://gitlab.com/staltz/manyverse/-/issues/1608

**Comment by senhuawang** [comment]
thanks
