### ISSUE TITLE
How do hashtags work?

### ISSUE THREAD

**Issue by nichoth** [staltz/manyverse#106]
Is there a view in the app of all the hashtags that are within your view? And if you click a hashtag, how is it indexed as to which posts contain the tag?

This is purely a documentation request. And thanks for taking the time to answer. I spent all night looking in the source code here, but didn't see anything that made sense to me.

I would expect one of the `secret-stack` plugins to do the indexing, but I didn't see one.

**Comment by staltz** [comment]
> Is there a view in the app of all the hashtags that are within your view?

No, not yet

> I would expect one of the `secret-stack` plugins to do the indexing, but I didn't see one.

Oh, it's implemented in ssb-threads
