### ISSUE TITLE
manyverse communicates with pub

### ISSUE THREAD

**Issue by scottwang2021** [staltz/manyverse#107]
Hello, staltz, I tested the function of the latest version of manyverse. Currently iOs and Android can find each other and communicate with each other under wifi, but I still have not been able to use manyverse to establish communication with pub, or to establish remote two manyverse devices through pub. For the communication between the pub, I followed through the invitation code, but I cannot receive the message sent by the pub, has the function of manyverse been completed?thank you for your reply.

**Comment by staltz** [comment]
Hi! It should be working, I'm not sure why it's not working. It could potentially be a problem with the pub too. Can you give more details? When you pasted the invite code, what happened after that?

**Comment by scottwang2021** [comment]
Thank you for your reply. I paste the invitation code of pub, you can follow to pub, and then use pub to send a public message. Manyverse cannot receive the pub message, but patchwork that also uses the invitation code can receive it.

**Comment by staltz** [comment]
Which pub was it? Do you know if it has `ssb-ebt` installed? (Or support for EBT replication)

**Comment by scottwang2021** [comment]
https://github.com/cryptoscope/ssb   We are using the go version of ssb and ebt. Which version of pub are you currently using? Can you provide a link? thanks

**Comment by scottwang2021** [comment]
This is a script, is there any wrong configuration：         go-sbot --debugdir=./debugdir --debuglis=192.168.2.121:6078 --enable-ebt --hops=2 --lis=192.168.2.121:8008  --localadv --localdiscov --promisc --repo="/home/cy/.ssb-go" --wslis=192.168.2.121:8989

**Comment by scottwang2021** [comment]
Hello, staltz, I have not received your suggestion. Can you provide a room invitation? I can test the communication through the room by manyverse. Thank you.

**Comment by staltz** [comment]
Hi, I'm not sure what is the bug you're experiencing, I haven't had enough information to understand what's going on, and debugging like this is difficult.
