### ISSUE TITLE
Add pubs in Sync screen

### ISSUE THREAD

**Issue by fuzzyTew** [staltz/manyverse#11]
Where can I paste a pub invite?

**Comment by staltz** [comment]
Can't yet, but it's on the roadmap.

**Comment by Musickiller** [comment]
So how do I start using MMMMM at all? Is there a FAQ anywhere?

**Comment by staltz** [comment]
It's not ready to be used yet, it's an alpha. There is one way of getting it to find pubs: sync with your desktop's Patchwork through a common WiFi, then the phone app will have access to the same pubs.

**Comment by Musickiller** [comment]
Wi-Fi only? I only have Android's RNDIS (Internet over USB tethering) for next 9 months...
