### ISSUE TITLE
How to clean up file storage after uninstalling desktop version

### ISSUE THREAD

**Issue by glyn** [staltz/manyverse#112]
I recently tried using manyverse on macOS, but I couldn't find where it was storing files locally and having uninstalled the application, I would like to delete those files. Please could you document or otherwise make clear where this directory resides.

**Comment by staltz** [comment]
This is well documented in our FAQ, just delete the data folder: https://www.manyver.se/faq/manyverse-folder-location

**Comment by glyn** [comment]
Thanks @staltz and apologies for not noticing the FAQ. I was looking under documentation in the README and didn't think to navigate via the homepage.
