### ISSUE TITLE
I don't get it...

### ISSUE THREAD

**Issue by ruifortes** [staltz/manyverse#129]
I just installed Manyverse on Windows and even joined a room but...
How the hell do I make a public post?
Where is the post or send button?

![Manyverse_KfP2xtSkD3](https://user-images.githubusercontent.com/4864714/152659588-8822ecde-861b-4f85-96bd-102fb8e92f59.png)

**Comment by staltz** [comment]
Press the preview button. We have a bug where the preview button might not work (we'll make a fix on Monday), but if you resize the window you may be able to press preview

**Comment by ruifortes** [comment]
ahh!! Thank God! I thought my cognitive decline was at full speed by now :-P

**Comment by Powersource** [comment]
hoping the new version fixed this
