### ISSUE TITLE
Could not get unknown property 'MYAPP_RELEASE_STORE_PASSWORD'

### ISSUE THREAD

**Issue by pietgk** [staltz/manyverse#14]
on 

```
react-native run-android 
```

i get

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/grop/dev/mmmmm-mobile/android/app/build.gradle' line: 123

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'MYAPP_RELEASE_STORE_PASSWORD'

```
i added the below lines to android/gradle.properties

```
MYAPP_RELEASE_STORE_FILE=""
MYAPP_RELEASE_STORE_PASSWORD=""
MYAPP_RELEASE_KEY_ALIAS=""
MYAPP_RELEASE_KEY_PASSWORD=""
```

as a temp fix for me.

i could use feedback if this is the direction to solve this for now.

- MMMMM app version: 0.08

**Comment by staltz** [comment]
Hi @pietgk :)
Thanks for letting us know.

That file with those variables are only needed when creating a release build, they are unnecessary for debug builds (the one that occurs when you run `react-native run-android`) but the android/app/build.gradle file nevertheless refers to those variables, so if they don't exist at all, it seems that the build is aborted.

So a decent fix would be to fix build.gradle to check if the variables exist before attempting to read them (if that's possible in the build.gradle syntax)
