### ISSUE TITLE
Electron desktop app

### ISSUE THREAD

**Issue by staltz** [staltz/manyverse#16]
Read `%rZ2JaPFcz5slehFitTf3/g6a2b6FiaVihsNWqlGHdw0=.sha256`

**Comment by buoyantair** [comment]
Can we know what's on the link o-o. It would be great to have a desktop app.

**Comment by staltz** [comment]
http://viewer.scuttlebot.io/%25rZ2JaPFcz5slehFitTf3/g6a2b6FiaVihsNWqlGHdw0=.sha256

**Comment by buoyantair** [comment]
Thank you!
