### ISSUE TITLE
Help with PR to prevent user-select of topBar title text

### ISSUE THREAD

**Issue by donuts-are-good** [staltz/manyverse#194]
Hello Staltz,

I'd like to PR the addition of the `user-select: none;` property, and `cursor: default;` to the behavior of the title to prevent behavior where selecting the menubar to reposition the window causes unintended selection, and prevents a text-edit cursor to be shown to the user when hovering. 

I'm a user of manyverse, so today is the first time seeing the code. Being unacquainted my first guess is possible these properties are applicable here, and if this PR is welcome, any guidance with regards of where to look would be appreciated.

https://github.com/staltz/manyverse/blob/17ef116e18a6f5166483d7abdec93121a9fd1c9e/src/frontend/screens/central/index.ts#LL69

Example of the behavior in question (unintended text selection)

<img width="490" alt="image" src="https://user-images.githubusercontent.com/96031819/222613778-70107c39-5563-46c9-adbc-c51beb8bbbff.png">

**Comment by staltz** [comment]
Oh, this is very neat tweak. Thanks.

The solution would be in the so-called "Top Bar" which is at src/frontend/screens/central/top-bar and for CSS properties you have to use `Platform.OS === 'web'` or `Platform.select`. If you search the codebase for `Platform.select` you'll find plenty of these and some of them are styles. In other words, be careful to not apply these styles on Android or iOS, just web.

Thanks!

**Comment by donuts-are-good** [comment]
https://github.com/staltz/manyverse/pull/196
