### ISSUE TITLE
Profile created with macOS Manyverse fails to import into iOS Manyverse app, which claims phrase is invalid

### ISSUE THREAD

**Issue by Nezteb** [staltz/manyverse#199]
I set up a profile on Manyverse for macOS and then got the recovery phrase:
<img width="1030" alt="CleanShot 2023-08-21 at 12 29 33@2x" src="https://github.com/staltz/manyverse/assets/3588798/4924ca9e-4d46-4e0a-b5bd-c44a5bb995a4">

I went through the "practice" modal that prompts you to re-enter your recovery phrase, and the app said I did it correctly.

Then I tried to set up the same profile on Manyverse for iOS but get an error that the recovery phrase isn't valid:
![photo_2023-08-21_12-30-40](https://github.com/staltz/manyverse/assets/3588798/9eb7bea3-2454-45e9-b1fa-8cdd6d69460a)

Any ideas? 😅

**Comment by staltz** [comment]
First of all, https://www.manyver.se/faq/account-on-many-devices

**Comment by Nezteb** [comment]
ACK, I can't believe I missed that bit. Disregard this issue.

Thanks!
