### ISSUE TITLE
Step-through welcome screens

### ISSUE THREAD

**Issue by staltz** [staltz/manyverse#20]
Take inspiration from Copay and Nordea Wallet

- [ ] (1) Social network like usual, but not centralized
- [ ] (2) All data on your phone ("can use in the airplane, but consumes storage space")
- [ ] (3) Freedom and responsibility
- [ ] (4) Beta! (not all features available, help us with bug reports)

**Comment by luandro** [comment]
A quick research led me to [react-native-swiper](https://github.com/leecade/react-native-swiper). Should we use it? I could try adding it.

**Comment by staltz** [comment]
Yeah! I was thinking about using one of these ready components. For the design, I was thinking full-screen with background in indigo color, a huge emoji for each section, and a text under that emoji. Later, the emoji would be replaced with a decent SVG illustration, but we need to find a designer to make those. :)
