### ISSUE TITLE
Level down not working in IOS/Android

### ISSUE THREAD

**Issue by Linoy339** [staltz/manyverse#69]
Hi all,
I am trying to establish offline db using pouch db in mobile.
I have an application which uses node express and pouch db. Its running well in my pc. I was able to take a build using webpack and tried in android/ios, which is not working.
IOS Error:
Error: No native build was found for platform=ios arch=arm64 runtime=node abi=57 uv=1 armv=8 libc=glibc at load.path (/private/var/mobile/Containers/Data/Application/74907299-A8BC-40E0-98CC-A5D65DDA491C/Documents/nodejs-project/api/node_modules/node-gyp-build/index.js:56:3)

Android Error:
Error: dlopen failed: cannot locate symbol "napi_get_global" referenced by "/data/data/digital.lamp.mindlamp/files/lampBuild/api/node_modules/leveldown/prebuilds/android-arm64/node.napi.armv8.node"...

**Comment by staltz** [comment]
Seems to be a leveldown issue, not a Manyverse one.
