### ISSUE TITLE
Not loading Profile Pic

### ISSUE THREAD

**Issue by afterconnery** [staltz/manyverse#82]
Running latest version from Google Play Store. (Version 0.2103.5-beta-googlePlay)
Android version is 10

I can choose a picture from my phone to use as profile pic and it does not come up to crop it or anything like it. Then the profile pic area is still empty.

**Comment by Powersource** [comment]
i think this might be fixed https://gitlab.com/staltz/manyverse/-/issues/1385 let us know if it still doesn't work!
