### ISSUE TITLE
[ios] add bluetooth feature

### ISSUE THREAD

**Issue by devsnor** [staltz/manyverse#85]
Iphones cannot sync based on bluetooth. 

It was mentioned [here](https://www.manyver.se/blog/2020-01-update) and the commits removing bluetooth for iOS are easily located ( [1](https://gitlab.com/staltz/manyverse/-/commit/3a3e0ac54766595cc6a9614997bbf324f7b2d366) and [2](https://gitlab.com/staltz/manyverse/-/commit/b23bf9adc2826f21b2d2556cc4a028c21766b265) ).
However, I don't really understand what are the technical issues behind this choice and if there is any plan to bring the bluetooth feature to iOS?
If the issue resolution can be developed and tested without iOS simulation, I can definitely try it on my own. (I don't have an iphone to test).

Many thanks.

**Comment by staltz** [comment]
Hi, thank you for taking your time to send us this issue. Bluetooth sync on iOS was never supported, those commits were just removing UI buttons for a feature that would not have worked anyway. The core logic for Bluetooth sync is done by the library https://github.com/Happy0/react-native-bluetooth-socket-bridge/ which is only implemented in Android. We would definitely appreciate if someone could update that library to implement it in ObjectiveC and Apple SDKs.

**Comment by Powersource** [comment]
moved this issue here https://gitlab.com/staltz/manyverse/-/issues/1620
