### ISSUE TITLE
Mobile data access pub

### ISSUE THREAD

**Issue by senhuawang** [staltz/manyverse#99]
Hello, we have installed manyverse on the mobile phone, but when using mobile data to connect to the pub, we have not successfully sent public and private messages. What is the reason for this situation?

**Comment by staltz** [comment]
Have you tried making sure that all the parties involved are "Follow"ing each other?

**Comment by senhuawang** [comment]
YES,I confirm that all the following parties are following each other, but the mobile phone enters the pub and cannot see other people

**Comment by Powersource** [comment]
hoping this got fixed, let us know otherwise!
